### ISSUE TITLE
Bluetooth RSSI Logic

### ISSUE THREAD

**Issue by PinPoh** [hsh0321/AR-Indoor-Navigation#1]
Hello, I've looking at your project and wondering how you get the RSSI Signal for the bluetooth beacon.
May I know where the specific part of code that tells me the RSSI and show it? Also which button may activate this function?
Thanks

**Comment by hsh0321** [comment]
Creating games using Unity often requires native implementation of functions when using Android notification (local push) or SNS functions that are not supported by Unity Plugin, but it was difficult to mount Android native functions in the Unity environment. Eventually, the JAR plug-in found a way to invoke the Java method in C# and the C# method in Java, and worked this out.

An example of an Android function call in Unity is:
[bleScan.cs](https://github.com/hsh0321/AR-Indoor-Navigation/blob/master/_Unity/Assets/Scripts/Button/bleScan.cs)
[locRefresh.cs](https://github.com/hsh0321/AR-Indoor-Navigation/blob/master/_Unity/Assets/Scripts/Button/LocRefresh.cs)

I made a Bluetooth-related function on Android and produced it in the form of aar and used it in the form of a plug-in inside Unity.
filepath : https://github.com/hsh0321/AR-Indoor-Navigation/tree/master/_Unity/Assets/Plugins/Android
